### ISSUE TITLE
为什么我写了依赖，但是不管用呢，界面并不会更新啊

### ISSUE THREAD

**Issue by XDMarkJacobs** [LeetCode-OpenSource/rxjs-hooks#1045]
![image](https://user-images.githubusercontent.com/49051362/185593493-4f1b88ee-3813-4509-9578-07be64e2e4de.png)

https://stackblitz.com/edit/react-ts-dvl5gx

**Comment by Miloas** [comment]
https://github.com/LeetCode-OpenSource/rxjs-hooks#known-issues

**Comment by Miloas** [comment]
Also you need upgrade `rxjs-hooks` to [v0.8.0-alpha.0](https://github.com/LeetCode-OpenSource/rxjs-hooks/releases/tag/v0.8.0-alpha.0)
