### ISSUE TITLE
suggest: default value can accept a observable, and use* function can return a subject as complementary for other propose

### ISSUE THREAD

**Issue by galenjiang** [LeetCode-OpenSource/rxjs-hooks#13]
I think, it is can give more choose to mutate the value in use* function scope.
eg: 
```javascript

<Timer defaultValue={of(0)} />
function Timer({ defaultValue /* both accept primary value or observable */}) {
    const [value, /* subject */] = useObservable(
        (inputs$) => {
            mergeMap(interval(1000).mapTo((v) => v + 1)),input$.map(v=> ()=> v)).scan((a,b)=>b(a),0)
        },
        defaultValue)
    return (
    <h1>{value}</h1>
  )
}
```

**Comment by zry656565** [comment]
hi, @galenjiang thanks for your feedback. First of all, I think it's not a good practice to pass an Observable as a prop in React, which makes code more unreadable. Could you provide more practical examples to prove your use case?

**Comment by zry656565** [comment]
Because there's no update here for a long time, I am going to close this issue. If you have any further question, feel free to reopen it.
