### ISSUE TITLE
Question: useEventCallback could take any callback signature besides SyntheticEvent?

### ISSUE THREAD

**Issue by f0rr0** [LeetCode-OpenSource/rxjs-hooks#14]
in the current implementation, it is assumed that `useEventCallback` will receive a react synthetic event. Is there any reason behind this assumption?

this does not let me use the callback on my custom event handlers.

For instance:

```tsx
const MyInput = ({ onChange, value }) => (
   <input onChange={e => onChange(e.target.value)} value={value} />
)
```

I can't use `useEventCallback` on `MyInput` because the type signature of `onChange` there is:
```ts
type onChange = (val: string) => void
```

**Comment by zry656565** [comment]
#17 will fix this problem. After it merged, we will publish a new version.

**Comment by f0rr0** [comment]
@zry656565 thanks for fixing this. Any idea when the new version will be published?
