### ISSUE TITLE
Optimization request: avoid rendering twice

### ISSUE THREAD

**Issue by jmike** [LeetCode-OpenSource/rxjs-hooks#33]
Hey,

I am using `RxJS.BehaviorSubject` which allows me to get the latest value at any given time. That said, my component looks a bit like this...

```javascript
const MyComponent = ({ subject$ }) => {
  const data = useObservable(() => subject$, subject$.getValue());
  return (
    <h1>{data.name}</h1>
  );
};
```

Also, in code-sandbox: https://codesandbox.io/s/jlkrpny969

The fact of the matter is that the component renders twice, although the initial state value is the same as the value returned from the inputFactory.

Would it be possible to avoid an extra render when the initial state matches the returned value?

**Comment by Brooooooklyn** [comment]
seems like we should `distinctUntilChanged` to the return value of `useObservable`

**Comment by icexxxxxx** [comment]
Hi @jmike, I'm use react 16.8.4 and I don't see any additional render with your code, would you like to have a try?

**Comment by jmike** [comment]
@icexxxxxx I confirm that there is no additional render with the latest react. Not sure how I missed this.

I've updated the codesandbox accordingly...
https://codesandbox.io/s/jlkrpny969

I am closing this issue. Thanks for the great support and all the hard work you put into this module.
