### ISSUE TITLE
Bug: Emit same object will not trigger re-render

### ISSUE THREAD

**Issue by csr632** [LeetCode-OpenSource/rxjs-hooks#91]
live demo: https://codesandbox.io/s/rxjs-hooks-bug-zuvek?fontsize=14

**Only newer version of react(with setState bail out feature) have this bug.** I use 16.10.2

---

I think the bug is caused by this line: 
https://github.com/LeetCode-OpenSource/rxjs-hooks/blob/203b98f858909aee10cad3fc25607e49ced5ce64/src/use-observable.ts#L54

If my observable emit same **mutable object** again and again, the subscriber component will not re-render.
Because setState will [bail out of updates if the next value is the same as the previous one](https://reactjs.org/docs/hooks-faq.html#is-there-something-like-forceupdate)

If the same **mutable object** contain different data among renders, we will not see the latest data.

**Comment by Brooooooklyn** [comment]
This behavior is by design, just the same as what React renderer behavior.

**Comment by csr632** [comment]
This is probably not a good idea. rxjs never teach its develops the idea of "immutability", and rxjs don't need the idea of "immutability".
Developer with rxjs experience is likely to get bugs(which is hard to debug) because of this.

**Comment by Brooooooklyn** [comment]
> rxjs never teach its develops the idea of "immutability", and rxjs don't need the idea of "immutability".

True, but `RxJS` is just a tool which help you manage your data stream. You are using React as your runtime.
Every React developer should consider about **Mutable** or **Immutable**,  and most of them will agree that mutate a *object* will not trigger rerender.

I believe if you were using `Angular` or `VueJS` you will not ask this question.
