### ISSUE TITLE
I cant calc the dom size

### ISSUE THREAD

**Issue by 454575238** [LeetCode-OpenSource/rxjs-hooks#93]
useObservable is never use in useEffect, but i wanna calc the dom size without some event

**Comment by Brooooooklyn** [comment]
Please provide some codes to show your usecase, I'm hardly understand your problem.

**Comment by 454575238** [comment]
useEffect(() => {
    const virtualListEle: HTMLDivElement = listContainerRef.current
    containerHeight$.next(virtualListEle.clientHeight)

    const actualRow$ = combineLatest(containerHeight$, props.options$).pipe(
      map(([ch, { height }]) => Math.ceil(ch / height)),
    )

    const dataInViewSlice$ = combineLatest(props.data$, actualRow$).pipe(
      map(([data, actualRows]) => data.slice(0, actualRows)),
    )
    const scrollHeight$ = combineLatest(props.data$, props.options$).pipe(
      map(([data, { height }]) => data.length * height),
    )

    sub.add(
      combineLatest(dataInViewSlice$, scrollHeight$).subscribe(
        ([data, height]) => {
          setData(data)
          seHeight(height)
        },
      ),
    )

    return () => {
      sub.unsubscribe()
    }
  }, [listContainerRef.current])

**Comment by zry656565** [comment]
It seems that rxjs-hooks isn't suitable for this case. So you may have to do the thing in your own style.

**Comment by fuwei-1993** [comment]
ok tks
